activation:
  approximate: tanh
  name: gelu
architecture:
  embeddings:
    bias: true
    hidden_dim: 256
    input_dim: 147
    n_layers: 3
  policy_head:
    bias: true
    hidden_dim: 256
    input_dim: 256
    n_layers: 3
    output_dim: 132
  value_head:
    bias: true
    hidden_dim: 256
    input_dim: 256
    n_layers: 2
    output_dim: 1
initializer: {}
loss:
  actor_loss:
    label_smoothing: 1.0e-06
    reduction: none
  critic_loss:
    reduction: mean
name: FCPolicyValueNet
optimizer:
  lr: 3.0e-05
  name: adam
  weight_decay: 1.0e-05
